import type { FoodItem } from './types';

export const foodData: FoodItem[] = [
  { name: 'Almonds', purines: 31, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Amazake (Fermented Drink Made From Sake Lees)', purines: 6, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Anchovy', purines: 304, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Anchovy (Dried)', purines: 1109, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Arabesque Greenling', purines: 150, category: 'Other', purineLevel: 'Medium' },
  { name: 'Asparagus', purines: 33, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Avocado', purines: 18, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Ayu', purines: 133, category: 'Other', purineLevel: 'Medium' },
  { name: 'Bacon (Meatless)', purines: 74, category: 'Meat', purineLevel: 'Low' },
  { name: 'Balsam Pear (Goya)', purines: 10, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Bamboo Shoots', purines: 47, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Bananas', purines: 3, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Barley', purines: 44, category: 'Grains', purineLevel: 'Low' },
  { name: 'Barracuda', purines: 148, category: 'Other', purineLevel: 'Medium' },
  { name: 'Bean Curd Lees (Okara)', purines: 49, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Bean Sprouts, With Bean', purines: 57, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Bean Sprouts, Without Bean', purines: 35, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Beans, Adzuki (Dried)', purines: 78, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Beef Brisket', purines: 79, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beef Chuck Ribs', purines: 77, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beef Clod (Shoulder)', purines: 104, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beef Front', purines: 77, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beef Heart', purines: 185, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beef Kidney', purines: 174, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beef Large Intestine', purines: 88, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beef Liver', purines: 220, category: 'Meat', purineLevel: 'High' },
  { name: 'Beef Neck', purines: 101, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beef Rib Loin', purines: 74, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beef Round (Topside)', purines: 123, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beef Round (Topside), Cooked', purines: 143, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beef Shin', purines: 106, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beef Sirloin', purines: 90, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beef Stomach', purines: 84, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beef Tongue', purines: 90, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beef, Tenderloin', purines: 98, category: 'Meat', purineLevel: 'Low' },
  { name: 'Beer For Export (Higher Wort Content Than Typical Austrian Lager)', purines: 11, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Beer, \'Regular\' Type, Various Brands', purines: 9, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Beer, Dark', purines: 14, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Beer, From Wheat', purines: 8, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Beer, Low Alcohol', purines: 5, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Beer, Pils', purines: 10, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Beltfish', purines: 139, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Bonito (Dried)', purines: 493, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Brandy', purines: 0, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Brassicaceae (Blossom)', purines: 27, category: 'Other', purineLevel: 'Low' },
  { name: 'Bread', purines: 4, category: 'Grains', purineLevel: 'Low' },
  { name: 'Bread Flour', purines: 26, category: 'Grains', purineLevel: 'Low' },
  { name: 'Broad Beans (Dried)', purines: 36, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Broccoli', purines: 70, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Broccoli Sprouts', purines: 130, category: 'Vegetables', purineLevel: 'Medium' },
  { name: 'Broccoli, Boiled', purines: 52, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Buckwheat Flour', purines: 76, category: 'Grains', purineLevel: 'Low' },
  { name: 'Burdock', purines: 5, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cabbage', purines: 3, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cabbage, Chinese (Pak-choi)', purines: 7, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cabbage, Chinese (Qing-geng-cai)', purines: 12, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cake Flour', purines: 16, category: 'Grains', purineLevel: 'Low' },
  { name: 'Carp', purines: 103, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Carrots', purines: 2, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cauliflower', purines: 57, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cayenne Pepper Powder', purines: 20, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cheese, Grated', purines: 13, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Chia Seeds', purines: 59, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Chicken (Meatless)', purines: 77, category: 'Meat', purineLevel: 'Low' },
  { name: 'Chicken Breast', purines: 141, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Chicken Gizzard', purines: 143, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Chicken Heart', purines: 224, category: 'Meat', purineLevel: 'High' },
  { name: 'Chicken Leg', purines: 118, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Chicken Liver', purines: 303, category: 'Meat', purineLevel: 'Very High' },
  { name: 'Chicken Skin', purines: 120, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Chicken Wing', purines: 138, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Chicken, Light Meat', purines: 111, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Chickpeas (Garbanzo Beans), No Further Specified', purines: 26, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Chocolate', purines: 8, category: 'Other', purineLevel: 'Low' },
  { name: 'Clams', purines: 145, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Cod', purines: 98, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Conger Eel', purines: 95, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Coriander', purines: 39, category: 'Other', purineLevel: 'Low' },
  { name: 'Corn', purines: 12, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Corned Beef', purines: 47, category: 'Meat', purineLevel: 'Low' },
  { name: 'Crab Ovary', purines: 152, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Crab, Red King', purines: 100, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Crab, Snow', purines: 137, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Cream, Animal', purines: 0, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Cream, Vegetable', purines: 0, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Cucumber', purines: 9, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Curry Roux', purines: 16, category: 'Other', purineLevel: 'Low' },
  { name: 'Cutlassfish (Hairtail)', purines: 386, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Eel, Japanese', purines: 92, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Egg White Schnitzel (Vegetarian \'Steak\')', purines: 39, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Egg, Chicken', purines: 0, category: 'Meat', purineLevel: 'Low' },
  { name: 'Egg, Quail', purines: 0, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Eggplant', purines: 51, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Engawa (Flesh Of Fish Fins)', purines: 19, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Fat Greenling', purines: 129, category: 'Other', purineLevel: 'Medium' },
  { name: 'Fish Ball, Processed', purines: 68, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Fish Product (Hanpen), Processed', purines: 13, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Fish Product (Kamaboko), Processed', purines: 26, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Fish Product (Narutomaki), Processed', purines: 32, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Fish Product (Sasakamaboko), Processed', purines: 48, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Fish Product (Satsuma Age), Processed', purines: 22, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Fish Sausage, Processed', purines: 23, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Fishcake Tube, Processed', purines: 48, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Flounder, Yellow Striped', purines: 113, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Flying Fish', purines: 154, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Foie Gras', purines: 82, category: 'Meat', purineLevel: 'Low' },
  { name: 'Frankfurter', purines: 50, category: 'Meat', purineLevel: 'Low' },
  { name: 'Frankfurter (Meatless)', purines: 32, category: 'Meat', purineLevel: 'Low' },
  { name: 'Fruit Juice', purines: 1, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Garland Chrysanthemum', purines: 47, category: 'Other', purineLevel: 'Low' },
  { name: 'Garlic', purines: 17, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Garlic Chives (Nira)', purines: 19, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Gelatin Noodle (Dried)', purines: 1, category: 'Grains', purineLevel: 'Low' },
  { name: 'Ginger Root', purines: 2, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Ginger, Japanese (Myoga)', purines: 8, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Gnomefish, Meat', purines: 151, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Gnomefish, Skin', purines: 383, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Goji Berry', purines: 6, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Green Beans', purines: 8, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Green Tea Beverage', purines: 2, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Green Tea Leaves (Dried)', purines: 204, category: 'Beverages', purineLevel: 'High' },
  { name: 'Halibut, Bastard', purines: 134, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Ham Style Vegetarian Slices, From Mycoprotein', purines: 117, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Ham, Pressed And Boneless Types', purines: 69, category: 'Meat', purineLevel: 'Low' },
  { name: 'Herring', purines: 139, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Honewort', purines: 12, category: 'Other', purineLevel: 'Low' },
  { name: 'Honey', purines: 1, category: 'Other', purineLevel: 'Low' },
  { name: 'Instant-vegetarian Dried \'Deer\' From Soy', purines: 116, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Instant-vegetarian Dried \'Fish\' From Soy', purines: 89, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Ketchup', purines: 11, category: 'Other', purineLevel: 'Low' },
  { name: 'Konnyaku', purines: 0, category: 'Other', purineLevel: 'Low' },
  { name: 'Leek, Japanese (Negi)', purines: 41, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Lettuce', purines: 5, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Lobster, Spiny', purines: 102, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Lotus Root', purines: 0, category: 'Other', purineLevel: 'Low' },
  { name: 'Luncheon Slices, Meatless', purines: 98, category: 'Other', purineLevel: 'Low' },
  { name: 'Mackerel', purines: 205, category: 'Seafood', purineLevel: 'High' },
  { name: 'Mackerel, Fermented (Heshiko)', purines: 207, category: 'Seafood', purineLevel: 'High' },
  { name: 'Mackerel, Jack, Half-dried', purines: 246, category: 'Seafood', purineLevel: 'High' },
  { name: 'Mackerel, Japanese, Skin', purines: 1175, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Mackerel, Spanish', purines: 162, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Malt Beverage, Including Non-alcoholic Beer', purines: 3, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Mayonnaise', purines: 1, category: 'Other', purineLevel: 'Low' },
  { name: 'Milk', purines: 0, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Milt, Cod', purines: 560, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Milt, Globefish', purines: 375, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Milt, Pigfish, Striped', purines: 306, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Mirin (Cooking Wine)', purines: 1, category: 'Other', purineLevel: 'Low' },
  { name: 'Miso', purines: 56, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Mizuna (Potherb Mustard)', purines: 20, category: 'Other', purineLevel: 'Low' },
  { name: 'Monkfish', purines: 70, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Monkfish Liver', purines: 104, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Monkfish Liver, Steamed', purines: 399, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Mushroom, Bunapii', purines: 31, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushroom, Hatakeshimeji', purines: 16, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushroom, Jew\'s Ear (Dried)', purines: 156, category: 'Vegetables', purineLevel: 'Medium' },
  { name: 'Mushroom, Tsukuritake', purines: 50, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushroom, Usu-hiratake', purines: 38, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushroom, White Aragekikurage', purines: 7, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushroom, White Hiratake', purines: 67, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushroom, Yamabushitake', purines: 34, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushroom, Yanagimatsutake', purines: 26, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushrooms, Bunashimeji', purines: 21, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushrooms, Enoki', purines: 49, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushrooms, Eringi', purines: 13, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushrooms, Hiratake', purines: 142, category: 'Vegetables', purineLevel: 'Medium' },
  { name: 'Mushrooms, Maitake', purines: 99, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushrooms, Nameko', purines: 19, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushrooms, Shiitake', purines: 23, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mushrooms, Shiitake (Dried)', purines: 312, category: 'Vegetables', purineLevel: 'Very High' },
  { name: 'Mustard', purines: 25, category: 'Other', purineLevel: 'Low' },
  { name: 'Mustard Spinach, (Komatsuna), Mature', purines: 11, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mustard Spinach, (Komatsuna), Young', purines: 39, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mutton', purines: 95, category: 'Meat', purineLevel: 'Low' },
  { name: 'Octopus', purines: 137, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Octopus Organs', purines: 80, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Okiami (Krill)', purines: 226, category: 'Seafood', purineLevel: 'High' },
  { name: 'Okra', purines: 40, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Onions', purines: 2, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Oysters', purines: 122, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Pacific Saury', purines: 155, category: 'Other', purineLevel: 'Medium' },
  { name: 'Pacific Saury, Half-dried', purines: 209, category: 'Other', purineLevel: 'High' },
  { name: 'Paprika, Red', purines: 1, category: 'Other', purineLevel: 'Low' },
  { name: 'Parsley', purines: 289, category: 'Vegetables', purineLevel: 'High' },
  { name: 'Parsley, Japanese', purines: 19, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Pastry Flour', purines: 26, category: 'Grains', purineLevel: 'Low' },
  { name: 'Pate, Liver', purines: 80, category: 'Meat', purineLevel: 'Low' },
  { name: 'Peanuts', purines: 49, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Peas, Green', purines: 22, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Peas, Green, Canned', purines: 19, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Peas, Podded', purines: 10, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Peas, Red (Dried)', purines: 25, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Pepper, Green', purines: 2, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Pepper, Green, Pickled', purines: 3, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Pepper, Red (Capsicum)', purines: 5, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Pepper, Red Green', purines: 1, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Pepper, Sweet, Green', purines: 69, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Perilla Leaves, Shiso', purines: 42, category: 'Other', purineLevel: 'Low' },
  { name: 'Pigfish, Striped', purines: 149, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Pork Heart', purines: 119, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Pork Kidney', purines: 195, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Pork Liver', purines: 285, category: 'Meat', purineLevel: 'High' },
  { name: 'Pork Neck', purines: 71, category: 'Meat', purineLevel: 'Low' },
  { name: 'Pork Ribs', purines: 76, category: 'Meat', purineLevel: 'Low' },
  { name: 'Pork Rump', purines: 113, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Pork Shoulder', purines: 94, category: 'Meat', purineLevel: 'Low' },
  { name: 'Pork Sirloin', purines: 91, category: 'Meat', purineLevel: 'Low' },
  { name: 'Pork Tenderloin', purines: 120, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Pork Tongue', purines: 104, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Pork, Bacon, Unprepared', purines: 62, category: 'Meat', purineLevel: 'Low' },
  { name: 'Potato', purines: 7, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Prosciutto (Parma Ham)', purines: 138, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Pumpkin', purines: 57, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Radish Leaf, Japanese', purines: 34, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Radish Root, Japanese', purines: 2, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Radish Sprouts, White', purines: 73, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Radler (Beer And Lemonade Mixture)', purines: 4, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Ramen, Noodle', purines: 22, category: 'Grains', purineLevel: 'Low' },
  { name: 'Red Seabream', purines: 129, category: 'Other', purineLevel: 'Medium' },
  { name: 'Rice Bran', purines: 100, category: 'Grains', purineLevel: 'Medium' },
  { name: 'Rice Crackers', purines: 14, category: 'Grains', purineLevel: 'Low' },
  { name: 'Rice Malt, Salted', purines: 14, category: 'Grains', purineLevel: 'Low' },
  { name: 'Rice, White', purines: 33, category: 'Grains', purineLevel: 'Low' },
  { name: 'Rockfish (Mebaru)', purines: 124, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Roe, Flying Fish, In Soy Sauce', purines: 92, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Roe, Mixed Species', purines: 81, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Sablefish Meat', purines: 123, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Sablefish Skin', purines: 67, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Sailfin Sandfish', purines: 98, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Sake', purines: 1, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Sake Lees', purines: 89, category: 'Other', purineLevel: 'Low' },
  { name: 'Salami', purines: 120, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Salmon, Canned', purines: 133, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Salmon, Chum', purines: 125, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Salmon, Mixed Species', purines: 119, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Sardine', purines: 211, category: 'Seafood', purineLevel: 'High' },
  { name: 'Sardine, Baby (Dried)', purines: 746, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Sardine, Fermented (Heshiko)', purines: 116, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Sardine, Half-dried', purines: 305, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Sauce, Barbecue', purines: 15, category: 'Other', purineLevel: 'Low' },
  { name: 'Sauce, Chili Bean, Chinese', purines: 9, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Sauce, Fish', purines: 93, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Sauce, Oyster', purines: 134, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Sausage (Meatless)', purines: 46, category: 'Meat', purineLevel: 'Low' },
  { name: 'Sausage, Vienna Type', purines: 46, category: 'Meat', purineLevel: 'Low' },
  { name: 'Scallops', purines: 77, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Sea Cucumber', purines: 8, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Sea Urchin', purines: 137, category: 'Other', purineLevel: 'Medium' },
  { name: 'Seabass, Japanese, Liver', purines: 218, category: 'Seafood', purineLevel: 'High' },
  { name: 'Seabass, Japanese, Skin', purines: 1400, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Seabass, Mixed Species', purines: 107, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Seaweed, Hijiki (Dried)', purines: 133, category: 'Vegetables', purineLevel: 'Medium' },
  { name: 'Seaweed, Kombu (Dried)', purines: 46, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Seaweed, Mozuku (Dried)', purines: 16, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Seaweed, Nori (Dried)', purines: 592, category: 'Vegetables', purineLevel: 'Very High' },
  { name: 'Seaweed, Wakame', purines: 262, category: 'Vegetables', purineLevel: 'High' },
  { name: 'Sesame', purines: 36, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Shad, Dotted Gizzard', purines: 187, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Shishamo With Roe, Half-dried', purines: 150, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Shochu (Japanese Spirit Liquor)', purines: 0, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Shoko-shu (Chinese Liquor)', purines: 10, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Shrimp', purines: 167, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Shrimp, Deep-water', purines: 222, category: 'Seafood', purineLevel: 'High' },
  { name: 'Shrimp, Raw (Sand Shrimp And Pacific Shrimp Species)', purines: 177, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Shrimp, Sakura (Dried)', purines: 749, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Smelt', purines: 95, category: 'Other', purineLevel: 'Low' },
  { name: 'Snails', purines: 182, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Soba (Buckwheat Noodles)', purines: 8, category: 'Grains', purineLevel: 'Low' },
  { name: 'Soup, Chinese Soup Type, Powdered', purines: 186, category: 'Other', purineLevel: 'Medium' },
  { name: 'Soup, Clam Chowder Type, Powdered', purines: 47, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Soup, Consommé Type, Powdered', purines: 180, category: 'Other', purineLevel: 'Medium' },
  { name: 'Soup, Matsutake Type, Powdered', purines: 234, category: 'Other', purineLevel: 'High' },
  { name: 'Soup, Potage Type, Powdered', purines: 38, category: 'Other', purineLevel: 'Low' },
  { name: 'Soup, Ramen Noodle, Dry', purines: 33, category: 'Grains', purineLevel: 'Low' },
  { name: 'Soup, Stock, Chinese (Dried)', purines: 509, category: 'Other', purineLevel: 'Very High' },
  { name: 'Soy Milk', purines: 22, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Soy Protein Concentrate, Produced By Acid Wash', purines: 192, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Soy Sauce Made From Soy And Wheat (Shoyu)', purines: 50, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Soybean, Black (Dried)', purines: 67, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Soybean, Fermented (Natto)', purines: 114, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Soybeans (Dried)', purines: 173, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Soybeans, Green', purines: 48, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Spaghetti', purines: 7, category: 'Grains', purineLevel: 'Low' },
  { name: 'Spinach, Boiled', purines: 39, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Spinach, Mature', purines: 51, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Spinach, Young', purines: 172, category: 'Vegetables', purineLevel: 'Medium' },
  { name: 'Squash, Zucchini', purines: 13, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Squid', purines: 151, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Squid Organs', purines: 60, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Squid, Shredded (Dried)', purines: 94, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Strawberries', purines: 2, category: 'Other', purineLevel: 'Low' },
  { name: 'Sweet Potato', purines: 17, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Swordfish (Xiphias)', purines: 132, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Taro', purines: 2, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Tilefish', purines: 120, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Tofu (Kinu)', purines: 20, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Tofu Burger', purines: 103, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Tofu, Boiled 3 Minutes', purines: 22, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Tofu, Boiled 5 Minutes', purines: 36, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Tofu, Deep-fried', purines: 54, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Tofu, Dried-frozen (Koyadofu)', purines: 292, category: 'Legumes', purineLevel: 'High' },
  { name: 'Tofu, Raw (Nigari)', purines: 31, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Tomatoes, Cherry Type', purines: 3, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Tomatoes, No Further Specified', purines: 7, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Trout, Rainbow', purines: 181, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Tuna', purines: 157, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Tuna (Bonito)', purines: 211, category: 'Seafood', purineLevel: 'High' },
  { name: 'Tuna, Canned', purines: 117, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Turbot Liver', purines: 264, category: 'Meat', purineLevel: 'High' },
  { name: 'Turbot Skin', purines: 142, category: 'Other', purineLevel: 'Medium' },
  { name: 'Turbot, European', purines: 112, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Turnip', purines: 4, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Udon (Wheat Noodles)', purines: 12, category: 'Grains', purineLevel: 'Low' },
  { name: 'Umami Broth, Powdered', purines: 685, category: 'Other', purineLevel: 'Very High' },
  { name: 'Ume Liqueur', purines: 0, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Vegetable Juice', purines: 14, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Vegetarian \'Ba Sa Fish\' From Soy', purines: 83, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Vegetarian \'Gizzard\' From Soy', purines: 0, category: 'Meat', purineLevel: 'Low' },
  { name: 'Vegetarian \'Meatloaf\' Or Patties', purines: 42, category: 'Other', purineLevel: 'Low' },
  { name: 'Vegetarian \'Quail\'s Eggs', purines: 0, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Vegetarian \'Steak\' From Wheat (Robi\' Schnitzels)', purines: 21, category: 'Grains', purineLevel: 'Low' },
  { name: 'Vegetarian Tender \'Shrimp', purines: 0, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Veggie Burgers Or Soyburgers, Unprepared', purines: 65, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Vegi \'Steak\' From Soy', purines: 62, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Vegideli Fish Style Fingers', purines: 67, category: 'Seafood', purineLevel: 'Low' },
  { name: 'Walnuts', purines: 20, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Wasabi', purines: 1, category: 'Other', purineLevel: 'Low' },
  { name: 'Weather Loach', purines: 136, category: 'Other', purineLevel: 'Medium' },
  { name: 'Whale', purines: 99, category: 'Meat', purineLevel: 'Low' },
  { name: 'Whiskey', purines: 0, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Whitebait (Dried)', purines: 471, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Whiting (Sillaginidae)', purines: 144, category: 'Other', purineLevel: 'Medium' },
  { name: 'Wine', purines: 1, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Yam, Japanese', purines: 4, category: 'Other', purineLevel: 'Low' },
  { name: 'Yeast (Dried)', purines: 847, category: 'Other', purineLevel: 'Very High' },
  { name: 'Yellowtail (Amberjack)', purines: 121, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Yellowtail, Young', purines: 153, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Yogurt', purines: 5, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Yogurt, Liquid', purines: 1, category: 'Dairy', purineLevel: 'Low' },
];
