import type { FoodItem } from './types';

export const foodData: FoodItem[] = [
  { name: 'Abalone', purines: 138, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'All-Bran Cereal', purines: 22, category: 'Grains', purineLevel: 'Low' },
  { name: 'Almonds', purines: 37, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Anchovies', purines: 411, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Apple', purines: 14, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Apricot', purines: 73, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Artichoke', purines: 78, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Asparagus', purines: 23, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Avocado', purines: 19, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Bacon', purines: 110, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Baker\'s Yeast', purines: 680, category: 'Other', purineLevel: 'Very High' },
  { name: 'Banana', purines: 57, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Bass', purines: 140, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Beef', purines: 133, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beef Kidney', purines: 200, category: 'Meat', purineLevel: 'High' },
  { name: 'Beef Liver', purines: 554, category: 'Meat', purineLevel: 'Very High' },
  { name: 'Beef Tongue', purines: 120, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Beer', purines: 18, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Beetroot', purines: 19, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Black Beans', purines: 36, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Black-eyed peas', purines: 45, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Bran', purines: 79, category: 'Grains', purineLevel: 'Low' },
  { name: 'Brazil Nuts', purines: 23, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Bread, White', purines: 17, category: 'Grains', purineLevel: 'Low' },
  { name: 'Bread, Whole Wheat', purines: 20, category: 'Grains', purineLevel: 'Low' },
  { name: 'Broccoli', purines: 81, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Brown Rice', purines: 85, category: 'Grains', purineLevel: 'Low' },
  { name: 'Brussels Sprouts', purines: 69, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cabbage', purines: 16, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Carp', purines: 160, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Carrot', purines: 17, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cashews', purines: 47, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Cauliflower', purines: 51, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Celery', purines: 19, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cheddar Cheese', purines: 6, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Cherries', purines: 7, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Chicken', purines: 175, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Chicken Broth', purines: 219, category: 'Other', purineLevel: 'High' },
  { name: 'Chicken Liver', purines: 243, category: 'Meat', purineLevel: 'High' },
  { name: 'Chickpeas', purines: 109, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Clams', purines: 136, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Cod', purines: 109, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Coffee', purines: 1, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Collard Greens', purines: 60, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Corn', purines: 22, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Cornflakes', purines: 19, category: 'Grains', purineLevel: 'Low' },
  { name: 'Crab', purines: 152, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Crayfish', purines: 147, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Cucumber', purines: 7, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Duck', purines: 138, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Eel', purines: 120, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Eggplant', purines: 21, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Eggs', purines: 9, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Fava Beans', purines: 32, category: 'Legumes', purineLevel: 'Low' },
  { name: 'Flounder', purines: 131, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'French Beans', purines: 37, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Goose', purines: 165, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Grapefruit', purines: 8, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Grapes', purines: 27, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Green Beans', purines: 37, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Green Peas', purines: 84, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Grouper', purines: 130, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Haddock', purines: 139, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Halibut', purines: 178, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Ham', purines: 131, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Hazelnuts', purines: 37, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Herring', purines: 210, category: 'Seafood', purineLevel: 'High' },
  { name: 'Kale', purines: 48, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Lamb', purines: 182, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Leeks', purines: 74, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Lentils', purines: 127, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Lettuce', purines: 13, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Lima Beans', purines: 122, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Lobster', purines: 118, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Mackerel', purines: 145, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Mango', purines: 11, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Milk, Skim', purines: 1, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Milk, Whole', purines: 1, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Mung Beans', purines: 222, category: 'Legumes', purineLevel: 'High' },
  { name: 'Mushrooms', purines: 58, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Mussels', purines: 112, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Mutton', purines: 96, category: 'Meat', purineLevel: 'Low' },
  { name: 'Navy Beans', purines: 190, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Noodles', purines: 22, category: 'Grains', purineLevel: 'Low' },
  { name: 'Oatmeal', purines: 58, category: 'Grains', purineLevel: 'Low' },
  { name: 'Octopus', purines: 139, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Okra', purines: 57, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Onion', purines: 13, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Orange', purines: 19, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Oysters', purines: 239, category: 'Seafood', purineLevel: 'High' },
  { name: 'Papaya', purines: 13, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Parsnips', purines: 23, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Partridge', purines: 122, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Peaches', purines: 10, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Peanuts', purines: 79, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Pears', purines: 12, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Pecans', purines: 17, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Perch', purines: 150, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Pheasant', purines: 153, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Pike', purines: 140, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Pineapple', purines: 19, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Pistachios', purines: 120, category: 'Nuts', purineLevel: 'Medium' },
  { name: 'Plums', purines: 12, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Popcorn', purines: 47, category: 'Grains', purineLevel: 'Low' },
  { name: 'Pork', purines: 166, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Potato', purines: 18, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Pumpkin', purines: 44, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Quail', purines: 137, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Rabbit', purines: 132, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Radish', purines: 15, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Raisins', purines: 107, category: 'Fruits', purineLevel: 'Medium' },
  { name: 'Raspberries', purines: 18, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Rhubarb', purines: 11, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Roe (Fish Eggs)', purines: 144, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Salmon', purines: 170, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Sardines (in oil)', purines: 480, category: 'Seafood', purineLevel: 'Very High' },
  { name: 'Scallops', purines: 151, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Shrimp', purines: 147, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Smelt', purines: 130, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Soy Milk', purines: 28, category: 'Beverages', purineLevel: 'Low' },
  { name: 'Soybeans', purines: 190, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Spinach', purines: 57, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Split Peas', purines: 135, category: 'Legumes', purineLevel: 'Medium' },
  { name: 'Squash', purines: 20, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Squid', purines: 154, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Strawberries', purines: 21, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Sunflower Seeds', purines: 64, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Sweet Potato', purines: 20, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Swordfish', purines: 140, category: 'Seafood', purineLevel: 'Medium' },
  { name: 'Tofu', purines: 55, category: 'Other', purineLevel: 'Low' },
  { name: 'Tomato', purines: 11, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Trout', purines: 297, category: 'Seafood', purineLevel: 'High' },
  { name: 'Tuna', purines: 257, category: 'Seafood', purineLevel: 'High' },
  { name: 'Turkey', purines: 150, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Turnips', purines: 16, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Veal', purines: 172, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Venison', purines: 138, category: 'Meat', purineLevel: 'Medium' },
  { name: 'Walnuts', purines: 25, category: 'Nuts', purineLevel: 'Low' },
  { name: 'Watercress', purines: 18, category: 'Vegetables', purineLevel: 'Low' },
  { name: 'Watermelon', purines: 8, category: 'Fruits', purineLevel: 'Low' },
  { name: 'Wheat Germ', purines: 130, category: 'Grains', purineLevel: 'Medium' },
  { name: 'White Rice', purines: 28, category: 'Grains', purineLevel: 'Low' },
  { name: 'Yogurt, Plain', purines: 8, category: 'Dairy', purineLevel: 'Low' },
  { name: 'Zucchini', purines: 21, category: 'Vegetables', purineLevel: 'Low' },
];
